name: book_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  # Iconos de Cupertino para iOS
  cupertino_icons: ^1.0.8
  # Sqlite para almacenamiento local
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  # Resolucion de directorios
  path: ^1.9.0
  # Provider para manejo de estado
  provider: ^6.0.0
  # Image Picker para seleccionar imagenes de la galeria
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_icon.png"
